### ISSUE TITLE
Test failure in 0.2.6 

### ISSUE THREAD

**Issue by max-baz** [Gskartwii/teehee#12]
Hi there,

I'm running tests as part of AUR package, and it shows one failed test, which I can also reproduce manually 😉 

It's mostly FYI, plus a suggestion to perhaps use Github Actions to run tests on main branch?

If you want, this works really well for my other rust project:

```yaml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --locked

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings
```

**Comment by TheBestTvarynka** [comment]
I'll deal with it tonight

**Comment by Gskartwii** [comment]
Hi, thanks for the heads-up! I made a mistake when updating the specification of the test case, and I've now fixed it in [v0.2.7](https://github.com/Gskartwii/teehee/releases/tag/v0.2.7). I'll be sure to add in the automated testing Action as soon as possible. Do let me know if there are any further issues with this release.

**Comment by max-baz** [comment]
Thanks! There is an issue of Cargo.lock being not up-to-date with Cargo.toml (it still shows 0.2.6 for example), so building the project with `--locked` flag (to make sure it uses dependency versions exactly as you wanted them to be) is failing. I think if you just do `cargo build` or any command, it will update it 👍

**Comment by max-baz** [comment]
I made a PR for you to play with, you can see how it fails now and how after updating Cargo.lock it should hopefully succeed: https://github.com/Gskartwii/teehee/pull/13

**Comment by Gskartwii** [comment]
Okay, I hope third time's the charm! For the sake of not overwriting Git tag history, I've created yet another release [v0.2.8](https://github.com/Gskartwii/teehee/releases/tag/v0.2.8). 😅
